### ISSUE TITLE
Can't cast spell (left hand only)

### ISSUE THREAD

**Issue by QnoisX** [CritLoren/Yggdrasil-VR#30]
**Describe the bug**
If you have a spell in your left hand and nothing in your right hand (empty hand) it will not let you cast.  The FX for casting plays, but when you release the trigger, nothing happens.  It also doesn't drain your magicka.  If you equip a weapon or spell in your right hand, the left will cast normally.  You can cast a spell in your right hand with your left hand being empty.

**To Reproduce**
1. Equip spell in left hand (menu, spell wheel, etc)
2. Empty your right hand (middle icon of spell wheel is fastest)
3. Try to cast the spell in your left hand.

**Expected behavior**
Spells in your left hand should cast just fine as long as you have enough magicka, no matter what your right hand is doing.

**Screenshots**
https://user-images.githubusercontent.com/109442605/181497275-110909f6-d52f-476f-8aef-de9a2f3d450e.mp4

**Save**
[newplayer.zip](https://github.com/m-vlad/Yggdrasil-VR/files/9209046/newplayer.zip)

**Crash log**
No crashing, just a bug.

**Desktop (please complete the following information):**
	OS: Microsoft Windows 11 Pro Insider Preview v10.0.25158
	CPU: AuthenticAMD AMD Ryzen 9 5950X 16-Core Processor            
	GPU #1: Nvidia GA102 [GeForce RTX 3090]
	GPU #2: Microsoft Basic Render Driver
	PHYSICAL MEMORY: 11.33 GB/31.91 GB
 - Antivirus [Windows Defender]

**Additional context**

**Comment by QnoisX** [comment]
SkySA has a left-hand blocking mechanic that's causing the problem.

**Comment by CritLoren** [comment]
Should be fixed with the update to SkySA 2.8
