### ISSUE TITLE
Spell Research Won't Close

### ISSUE THREAD

**Issue by crrowenson** [CritLoren/Yggdrasil-VR#32]
**Describe the bug**
When I activate the Research Journal, the spell research popup menu appears as expected, but if I move all the way to the right and click "nothing" to exit out, the menu closes but I cannot move and then it reopens automatically a few seconds later
**To Reproduce**
1. Go to inventory and activate the Research Journal
2. Click on 'nothing' or 'do nothing' (don't remember the exact term) to close out of the menu
3. wait and the menu should pop up again after a few seconds creating an infinite loop I can only escape by forcing the game to close

**Expected behavior**
The menu should just close down and let me return to the game as normal

**Desktop (please complete the following information):**
 - OS version: Windows 11
 - RAM: 16gb
 - CPU: AMD Ryzen 7 4800HS with Radeon Graphics
 - GPU: NVIDIA GeForce GTX 1660 Ti
 - Storage type Yggdrasil VR is installed on: internal SSD
 - Antivirus: Windows Defender

[Save12_8F9C23C6_0_53616C75757261_RiftenBeeandBarb_000122_20220728111949_1_1.zip](https://github.com/m-vlad/Yggdrasil-VR/files/9209505/Save12_8F9C23C6_0_53616C75757261_RiftenBeeandBarb_000122_20220728111949_1_1.zip)

**Comment by MichailLavreek** [comment]
Had the same bug, its happens to me when I open the research journal again in the middle of already happening research and click research again. Fixed somehow with opening crafting stuff and close menu

**Comment by CritLoren** [comment]
We'll be moving to Dino's Spell Discovery starting next version most likely (and even if not, likely moving away from Spell Research)
