### ISSUE TITLE
Soul Trap spells and effects not capturing souls.

### ISSUE THREAD

**Issue by InvisaWizard** [CritLoren/Yggdrasil-VR#34]
**Describe the bug**
the soul trap effect is not working as intended, I can see it being applied to the enemy, but when they die it is not trapping their souls. I am using Soul Cloak and the Soul Reap spells. After disabling GIST and loading into the save, I can trap souls like normal. Changing GIST configurations in the MCM did not resolve the issue.

**To Reproduce**
1. Ensure soul gems of appropriate level are in inventory
2. Find an enemy to soul trap
4. Soul trap the enemy
5. kill the enemy
6. See error, no soul is captured.

**Expected behavior**
trapping a soul will fill a gem of the appropriate level.

**Save**

[Saves.zip](https://github.com/m-vlad/Yggdrasil-VR/files/9227869/Saves.zip)
Here's a save with the spells in a dungeon with several common tier enemies

**Desktop (please complete the following information):**
 - OS version: [Windows 10]
 - RAM: [16gb]
 - CPU: Intel i5 - 11600KF @3.90GHz
 - GPU: Nvidia GTX 3060
 - Storage type Yggdrasil VR is installed on: SSD
 - Antivirus Windows Defender

**Additional context**
QnoisX in discord hasn't been able to replicate the issue.

**Comment by QnoisX** [comment]
Enabling the esp for GIST fixes this issue, so something must be wrong with the merge.

**Comment by CritLoren** [comment]
Should be fixed in 2.0-5, I forgot to include the relinker output.
