### ISSUE TITLE
Signposts Not Activating

### ISSUE THREAD

**Issue by SPLUMBAR** [CritLoren/Yggdrasil-VR#39]
Cannot interact with signposts for fast travel once you're a few hours into your game. This is a [reported bug on the mod's nexus page ](https://www.nexusmods.com/skyrimspecialedition/mods/51567?tab=bugs) that has gone unfixed, although there is a temporary fix with console commands. This temporary fix is using the console command _stopquest aSOS_SignFinderQuest_ and then _startquest aSOS_SignFinderQuest_ however this has to be done almost every time you want to fast travel with a signpost even in the same play session.

**Comment by CritLoren** [comment]
Not much I can do, but I'll include this in the FAQ at some point. will leave the issue open until I get around to it.

**Comment by DemandedFanatic** [comment]
I don't know a whole lot about how all this works, but I noticed that there seems to be a signpost added by blackthorn that is not bugged in this way, right outside of the town. Would it be possible to simply replace all the existing signs with copies of that one as a work-around?

**Comment by CritLoren** [comment]
We'll be moving to https://www.nexusmods.com/skyrimspecialedition/mods/71147 next update, so this problem should be gone too.
