### ISSUE TITLE
New Squad 2.0

### ISSUE THREAD

**Issue by QnoisX** [CritLoren/Yggdrasil-VR#42]
**Is your feature request related to a problem? Please describe.**
More followers is always welcome.  There's a squad of 3 new followers on Nexus that all have all the bells and whistles, custom voices, custom frameworks, they all chat with each other, etc.  The aware followers that chat amongst themselves is always fun.

**Describe the solution you'd like**
Maybe add the squad?  Either just the more the merrier or swap out some of the existing ones (not Auri).  I know M'rissi is pretty buggy.  Her questline just froze last time I tried to run it.  Still a good character if you can get her unlocked at the least.  Not a super fan of Bardin, he's just kinda meh.  He seemed to repeat a few lines over and over, got old.  Taina is supposed to be a healer but is pretty much just a standard follower with a custom look.  Inigo, Auri, and Lucien are all wonderful.  They're Squad 1.0.  Never played with Kaidan or Hoth, so no opinion on them.

**Is there already a mod that could solve this?**
**Thogra gra-Mugur**
![x1](https://user-images.githubusercontent.com/109442605/182739629-21f122e3-7122-4037-812b-f3da38862614.jpeg)
https://www.nexusmods.com/skyrimspecialedition/mods/58979

**Remiel w/ Dwemer buddy**
![x2](https://user-images.githubusercontent.com/109442605/182739878-c55f456e-1dc9-46b4-aae1-e610d2d2d14b.jpg)
https://www.nexusmods.com/skyrimspecialedition/mods/51874

**Xelzaz the Argonian**
![x3](https://user-images.githubusercontent.com/109442605/182739910-53dac29d-53dd-4076-b207-fba8471e1977.jpg)
https://www.nexusmods.com/skyrimspecialedition/mods/62893

**Describe alternatives you've considered**
Hanging out with Auri like usual.

**Additional context**

**Comment by QnoisX** [comment]
Remiel is pretty cool.  Has a good personality and her personal quest goes along with a vanilla quest and enhances it.  At the end of the first quest, she gains the little spider bot which comes out and helps in combat.  She's pretty terrible at combat herself.
![ScreenShot5](https://user-images.githubusercontent.com/109442605/183622023-d96cb84c-bf2b-45ef-b22d-59204bf4f286.png)

**Comment by CritLoren** [comment]
Followers list will be expanded in the next update, those look like good additions.
