### ISSUE TITLE
A Yggdrasil Compendium

### ISSUE THREAD

**Issue by Clonephaze** [CritLoren/Yggdrasil-VR#48]
The modpack does not have a built in description or any tips and tricks in book form. 

**Describe the solution you'd like**
Use this! I have included the esp for the book I made along with some screenshots of what it looks like in game and in inventory. The Pastebin link includes all text in the book if you'd like to read whats in it. 

**Is there already a mod that could solve this?**
No but I made one.

[Yggdrasil a refernce guide.zip](https://github.com/m-vlad/Yggdrasil-VR/files/9295110/Yggdrasil.a.refernce.guide.zip)
https://pastebin.com/1QrKswXJ

**Comment by Clonephaze** [comment]
Please let me know if there's other information you'd like added or anything you'd like changed

**Comment by Clonephaze** [comment]
Q has pointed out that there's a couple more things I meant to add. I'll add a section on magic arrows and time to blocks later. If anyone has anything else they think should be added please let me know.

**Comment by Clonephaze** [comment]
[Uploading Yggdrasil compendium.zip…](Yggdrasil Compendium)
Updated file with archery and timed blocks

**Comment by Clonephaze** [comment]
[Uploading Yggdrasil compendium.zip…]()

**Comment by RedBeardedRob** [comment]
Thank you Clonephaze. I read the pastebin and already learned things I didn't know
