### ISSUE TITLE
Possible removal of Random Guard Dialogues

### ISSUE THREAD

**Issue by Clonephaze** [CritLoren/Yggdrasil-VR#49]
**Is your feature request related to a problem? Please describe.**
Kind of. The pack seems pretty clearly balanced towards realism and immersion. It is very un-immersive when you suddenly hear a robot saying they stepped in dog shit. Skyrim has remarkably little cussing in it and this mod throws quite a few jarring lines in with modern cursing. Maybe if they cursed in a way that made sense, but its very much modern cursing. "Fucking Dragons" "My wife is cheating on me with the other guard" (bruh I don't even know you from that guard.) "Fucking kids won't stop running around" "My balls itch" etc etc. 

**Describe the solution you'd like**
A guard dialogue replacement mod that maybe doesn't throw in modern day cussing with a robot voice.

**Is there already a mod that could solve this?**
Maybe, there is [Guard Dialogue Overhaul](https://www.nexusmods.com/skyrimspecialedition/mods/22075) but I have zero idea how compatible it is. 

**Describe alternatives you've considered**
Removing the mod but I don't want to break anything. 

**Additional context**

**Comment by CritLoren** [comment]
I forgot to mention that in the last update I removed quite a few of the lines in that mod.
