### ISSUE TITLE
Nighteye spell/effect is not working with Beware of Darkness moving speed reduction

### ISSUE THREAD

**Issue by MichailLavreek** [CritLoren/Yggdrasil-VR#51]
**Describe the bug**
Help/FAQ is says that Night eye spell will help with moving speed reduction in the dark but its not. Candlelight spell helps, wearing the lantern helps but night eye is not.

**To Reproduce**
1. Be not a khajiit or vampire or werewolf.
2. Buy a Nighteye spell tome at the college, learn it, it grants Nighteye power (not the spell).
3. Go to the dark area, use Nighteye power.
4. Continue to move slowly as f.

**Expected behavior**
Move with normal speed like when using Candlelight spell.

**Save**
here is the save of the character in the dark area with Nighteye power available 
[saves.zip](https://github.com/m-vlad/Yggdrasil-VR/files/9315636/saves.zip)

**Desktop (please complete the following information):**
OS version: Windows 10
RAM: 16gb
CPU: ryzen 3700
GPU: RTX 1080 ti
Storage type Yggdrasil VR is installed on: SSD
Antivirus Windows Defender

**Additional context**
That speed reduction is making me crazy, I wish its to be optional.

**Comment by CritLoren** [comment]
Beware the Darkness will be removed.
