### ISSUE TITLE
Two copies of spell tomes

### ISSUE THREAD

**Issue by QnoisX** [CritLoren/Yggdrasil-VR#53]
**Describe the bug**
When you learn a new spell by reading the tome, you end up with 2 copies of the tome.  Probably Grimoire adding the tome since you need to for that mod to work.

**To Reproduce**
1. Go to inventory.
2. Click on spell tome of spell you don't know.
3. Successfully learn the spell.

**Expected behavior**
You should just keep the tome without destroying it.

**Screenshots**
N/a

**Save**
Don't have one atm.

**Crash log**
Doesn't crash the game, just weird.

**Additional context**
No context.

**Comment by QnoisX** [comment]
Fix for this was included with the Spell Tutor changes.
#14

**Comment by CritLoren** [comment]
Fixed in 2.0-5
