### ISSUE TITLE
Project AHO questline stuck - "No Corpse, No case" quest stuck due to mod conflict

### ISSUE THREAD

**Issue by Finitoz** [CritLoren/Yggdrasil-VR#56]
**Describe the bug**
Project AHO quest No Corpse, No case, requires the player to lift a vampires dead body into a barrel of acid. The body however has been turned into an ash pile by another mod so the entire questline is stuck.

**To Reproduce**
Just play Project AHO No Corpse, No case quest

**Expected behavior**
There should be a body on the floor to lift. 

**Screenshots**

**Save**
Add a save to reproduce your problem. You can find them at `Yggdrasil VR/profiles/Yggdrasil/saves`.
It's saying file type not supported, I'm probably doing something wrong here...

**Crash log**
not applicable

**Desktop (please complete the following information):**
should not be relevant i believe

**Additional context**
(https://tes-mods.fandom.com/wiki/No_Corpse,_No_Case)
This is a known issue according to the wiki - I copied the relevant line. Neither myself nor QnoisX could identify which mod exactly was doing this ask pile thing. 

No Vampire Body - it is ash:
Mods that alter vampirism, such as "Sacrosanct - Vampires of Skyrim" or "Sanguinaire" is likely to be causing this issue.
The solution is to disable the vampirism mod before starting this quest, and then after you have completed this quest - you can re-enable said mod afterwards.

**Comment by Finitoz** [comment]
Adding my latest save file. 
[ProjectAHOsaves.zip](https://github.com/m-vlad/Yggdrasil-VR/files/9356801/ProjectAHOsaves.zip)

**Comment by Finitoz** [comment]
Disabling "Vampyrium-Resurrected (Vampire Overhaul)" right before the quest started made the body appear correctly and allowed the quest to progress.

I added a save right that's right before accepting the quest so this can be reproduced. 

[RightBeforeQuestStart.zip](https://github.com/m-vlad/Yggdrasil-VR/files/9378171/RightBeforeQuestStart.zip)

**Comment by CritLoren** [comment]
Do you know what the name of the vampire is? Is it the N'wah? I could make a quick patch probably for this one vampire.

**Comment by Finitoz** [comment]
Yes, N'wah is the vampire.

**Comment by CritLoren** [comment]
[Vampyrium - Project AHO Patch.zip](https://github.com/CritLoren/Yggdrasil-VR/files/9396362/Vampyrium.-.Project.AHO.Patch.zip)
Try this.

**Comment by QnoisX** [comment]
![ScreenShot106](https://user-images.githubusercontent.com/109442605/186013185-1bbcdfca-a1eb-4b82-beb5-4542e86ccc20.png)

![ScreenShot107](https://user-images.githubusercontent.com/109442605/186013189-84fb6e36-8a58-4358-9ff4-220e7a274c1d.png)

Patch works.
