### ISSUE TITLE
Game goes to 'Loading' screen constantly when fighting

### ISSUE THREAD

**Issue by oolatek1** [CritLoren/Yggdrasil-VR#57]
**Describe the bug**

While playing, eventually it seems my saves become corrupt and i cannot continue.   This manifests with a constant 'Loading' screen popping up mid-game, and more often than not, just as a fight is triggered.    Sometimes this screen lasts 20-30 seconds, others it will freeze the game and require a forced shutdown.

**To Reproduce**

Begin a battle.   Seems to happen more often underground or in dungeons.   Note i typically have my two Daedric Honors Guards up and equipt with crescents
 
**Expected behavior**

Frozen loading screen that stops game entirely, or if it does go back into game, will continue to pop up again constantly after the first incident making playing impossible

**Screenshots**
**Save**

Attaching

**Crash log**

**Desktop (please complete the following information):**
 - OS version:Windows 10
 - RAM: [32gig
 - CPU: [e.g. Intel i7-9770
 - GPU: [e.g. Nvidia RTX 3080
 - Storage type Yggdrasil VR is installed on: ssd
 - Antivirus [e.g. Windows Defender, avg
**Additional context**
[freezing save.zip](https://github.com/m-vlad/Yggdrasil-VR/files/9365926/freezing.save.zip)

**Comment by CritLoren** [comment]
Follow the performance tips in the FAQ to reduce CPU overhead.
