### ISSUE TITLE
Why do I die whenever I learn a new spell.

### ISSUE THREAD

**Issue by SHOTTYDOTTY** [CritLoren/Yggdrasil-VR#60]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Save**
Add a save to reproduce your problem. You can find them at `Yggdrasil VR/profiles/Yggdrasil/saves`.

**Crash log**
If applicable, add a save to reproduce your problem. You can find them at `My Documents/My Games/Skyrim VR/SKSE/` where they'll be named something like `crash-2021-12-20-23-21-37.log`.

**Desktop (please complete the following information):**
 - Yggdrasil VR version: [e.g. 2.0-4, 2.0-5]
 - Storage type Yggdrasil VR is installed on: [e.g. SSD, HDD]
 - OS version: [e.g. Windows 11, Windows 10]
 - RAM: [e.g. 16gb, 32gb]
 - CPU: [e.g. Intel i7-9750H]
 - GPU: [e.g. Nvidia RTX 2060 Mobile]
 - Antivirus [e.g. Windows Defender, Bitdefender]

**Additional context**

**Comment by CritLoren** [comment]
I need details, saves, something lol
