### ISSUE TITLE
CTD when entering whiterun.

### ISSUE THREAD

**Issue by teknikalarkitekt** [CritLoren/Yggdrasil-VR#61]
**Describe the bug**
Crash to desktop with no error or freeze, just instant death, "there was no sound, he just died" type shit.

**To Reproduce**
1. Enter whiterun
2. Crash to desktop

**Expected behavior**
See inside of whiterun

**Screenshots**

**Save**
Add a save to reproduce your problem. You can find them at `Yggdrasil VR/profiles/Yggdrasil/saves`  https://drive.google.com/drive/folders/1PAuvOi2_8scVeQuA25V5JXxsJBRxTCr1?usp=sharing

**Crash log**
If applicable, add a save to reproduce your problem. You can find them at `My Documents/My Games/Skyrim VR/SKSE/` where they'll be named something like `crash-2021-12-20-23-21-37.log`.  https://drive.google.com/drive/folders/1PAuvOi2_8scVeQuA25V5JXxsJBRxTCr1?usp=sharing

**Desktop (please complete the following information):**
 - Yggdrasil VR version: [e.g. 2.0-4, 2.0-5]I don't know. I installed the latest version on september 13 2022
 - Storage type Yggdrasil VR is installed on: [e.g. SSD, HDD] samsung 850 evo 2TB SSD
 - OS version: [e.g. Windows 11, Windows 10] Windows 10
 - RAM: [e.g. 16gb, 32gb] 32gb
 - CPU: [e.g. Intel i7-9750H] AMD Ryzen 5 3600
 - GPU: [e.g. Nvidia RTX 2060 Mobile] Nvidia GeForce RTX 3070
 - Antivirus [e.g. Windows Defender, Bitdefender] Malwarebytes Antimalware Pro

**Additional context**
I installed 2 additional mods. CL's Dawnbreaker ii which is a mesh replacement for dawnbreaker (and a damn beautiful one at that) and daedric dawnbreaker, which changes the effects of dawnbreaker to make it seem really legendary. When I have time, I will be removing daedric dawnbreaker and trying again as I've just been told there is already a mod that overhauls the effectiveness of legendary weapons like the dawnbreaker

**Comment by teknikalarkitekt** [comment]
problem solved. I don't know if it was a 1 time occurance or the fact that I removed the daedric dawnbreaker mod that fixed it

**Comment by CritLoren** [comment]
Cool, FYI modified lists are not supported, so please ask for support in the #modifications channel on the discord only, otherwise this can cause confusion (especially to me if I cannot replicate an issue or if I know for a fact something shouldn't be causing problems).

Also for when you do post issue reports here, attach the logs and save files directly, save files will need to be zipped, but logs should be postable as is.

**Comment by teknikalarkitekt** [comment]
it looks like CL dawnbreaker ii mesh works with your mod pack without bringing up any errors, I would like to formally suggest it as an optional mod in place of the rapier one... CL dawnbreaker is so beautiful, look at this magnificent creation https://www.nexusmods.com/skyrimspecialedition/mods/37924
