### ISSUE TITLE
Vampire drain not effected by apprentice stone

### ISSUE THREAD

**Issue by oejma** [CritLoren/Yggdrasil-VR#73]
**Describing the bug**
As the title states, Vampire Drain is not effected by the apprentice stone. The Novice level spell should not cost magicka when cast but it does. (Have not tested other vampire spells)

**To Reproduce**
Just use Vampire Drain while under the effect of the apprentice stone.

**Expected behavior**
It should not drain magicka

**Comment by CritLoren** [comment]
Please follow the bug report template... I need saves, I can't just waste time setting up the same scenario when looking into these issues.
