### ISSUE TITLE
blue outline

### ISSUE THREAD

**Issue by jocira** [CritLoren/Yggdrasil-VR#76]
(first of all english is not my main language so have an open mind reading this)

**Describe the bug**
blue circular outline arround my visual field, blinking

**To Reproduce**
just started the game, everything else goes just perfect

**Desktop (please complete the following information):**
 - Yggdrasil VR version: last
 - HDD
 - OS version: win 10
 - RAM: 40
 - CPU: i7
 - GPU: 1070 ti
 - Antivirus karspersky

**Comment by CritLoren** [comment]
https://github.com/m-vlad/Yggdrasil-VR/wiki/FAQ
Please check faq before making posts.

Also when I ask for the yggdrasil version, please put the number in next time, thanks.
