### ISSUE TITLE
More mods in the optional section

### ISSUE THREAD

**Issue by DemandedFanatic** [CritLoren/Yggdrasil-VR#79]
**Is your feature request related to a problem? Please describe.**
I'd like to see some more mods relegated to the optional section, to create a divide between casual and hardcore play. Not everyone has the time or patience to constantly trek all across skyrim to the next dungeon, or wants to constantly eat and drink to keep stats up 

**Describe the solution you'd like**
Survival/map/signpost fast travel/learning spells or any other mods that could be considered part of a hardcore experience should be made toggleable so individuals can choose whether or not they want to partake in a casual or hardcore experience with minimal fussing with MCMs on their end

**Is there already a mod that could solve this?**
All the mods are there, this is more of a configuration issue

**Describe alternatives you've considered**
I mean I CAN edit these things myself (and have lol) but this is about end-user experience not whether I can technically do it

**Additional context**
Pretty please with a cherry on top

**Comment by CritLoren** [comment]
I might have some quick documentation on the easy mods to switch that have gotten frequent requests, but ultimately it's those mods that add the Yggdrasil flavour to me, and removing them would make that a boring way to play that I'd have to maintain. There are way more lists out there now than there were at this list's inception, there's certainly quite a few lists out there to pick from, if my direction doesn't suit your playstyle and you'd rather not mess with things.
