### ISSUE TITLE
CTDs occasionally accompanied by buzzing.

### ISSUE THREAD

**Issue by FluffyButtGaming** [CritLoren/Yggdrasil-VR#87]
Getting crashes to desktop (steam vr will still be open) regularly. Mostly when some enemies are spawning in near me or when I'm going through a door load (crashes when I click the door to load new area). There is a chance when it crashes to start a constant buzzing sound in the headset. I have a monster PC, so RAM/GPU/CPU should be non-issue. Using Quest 2 over airlink.

**To Reproduce**
There aren't set specific steps. I'm early game and just playing normally. I'm not doing anything crazy. Mostly just walking around and looking at stuff near Whiterun and Riverwood. One crash happened going towards Redoran's Retreat when a vampire spawned in, while others have happened going through doors in Whiterun, approaching Whiterun on foot, or even gathering an ingredient.

**Expected behavior**
I just get random CTDs. New to Skyrim VR and Mods so I'm assuming and hoping it isn't normal to get around 5 crashes in 3 hours.

**Screenshots**
I have a VOD of a recent stream here. https://www.twitch.tv/videos/1725582537 Couple of examples with timestamps: 
Crash happened just after 1:12 upon leaving Whiterun. Another just after 2:07 after picking up an ingredient. 

[New Compressed (zipped) Folder.zip](https://github.com/CritLoren/Yggdrasil-VR/files/10572354/New.Compressed.zipped.Folder.zip)

**Crash log**
[crash-2023-02-02-03-35-14.log](https://github.com/CritLoren/Yggdrasil-VR/files/10572377/crash-2023-02-02-03-35-14.log)
[crash-2023-02-02-04-29-55.log](https://github.com/CritLoren/Yggdrasil-VR/files/10572378/crash-2023-02-02-04-29-55.log)
[crash-2023-02-02-04-42-23.log](https://github.com/CritLoren/Yggdrasil-VR/files/10572379/crash-2023-02-02-04-42-23.log)
[crash-2023-02-02-05-17-44.log](https://github.com/CritLoren/Yggdrasil-VR/files/10572381/crash-2023-02-02-05-17-44.log)
[crash-2023-02-02-05-29-59.log](https://github.com/CritLoren/Yggdrasil-VR/files/10572382/crash-2023-02-02-05-29-59.log)

**Desktop**
 - Yggdrasil VR version: not sure where to see this, but this is the latest version as of 2/2/23
 - Storage type Yggdrasil VR is installed on: 2TB M.2 PCIe 4.0 SSD
 - OS version: Windows 11 Pro
 - RAM: 64GB of 4800 MHz DDR5 RAM
 - CPU: 13th Gen Intel(R) Core(TM) i9-13900KF   3.00 GHz
 - GPU: NVIDIA GeForce RTX 4090 (24GB GDDR6X)
 - Antivirus: Avast One

**Comment by CritLoren** [comment]
Have you disabled or added anything to the list?

**Comment by FluffyButtGaming** [comment]
> 

Not at all. The only thing I set was my height in the autosneak mod as your instructions stated.

**Comment by CritLoren** [comment]
Curious, all of those logs show different crashes, but primarily occlusion related. Could you try reinstalling the list but with the AV temporarily off?

**Comment by FluffyButtGaming** [comment]
AV off? Sorry I'm new to this. What is it and where do I turn it off?

**Comment by CritLoren** [comment]
antivirus, sorry.

**Comment by FluffyButtGaming** [comment]
Oh my bad. I realized after I hit enter lol. Yeah I can try that but it'll be later tonight or tomorrow morning. Should I test the game itself with it off to check for crashes afterward and update here?

**Comment by CritLoren** [comment]
probably not needed afterwards as long as you've set up the proper exclusions, this is just in case it's affecting how mods and stuff get installed.

**Comment by FluffyButtGaming** [comment]
Ok. I'll give that a shot and get back to you here with an update tonight or tomorrow.

**Comment by FluffyButtGaming** [comment]
Not more CTDs, so that must have did it. Thanks Crit.
