### ISSUE TITLE
Wyrmstooth Mod CTD

### ISSUE THREAD

**Issue by SamielLJackson** [CritLoren/Yggdrasil-VR#88]
Wyrmstooth crash, After leaving the burrow the imperial army wants to fight the dragon wyrmstooth. When i get to the village where the dragon is flying above head the game ctds. My guess is there are too many actors and the army is causing the crash.

**To Reproduce**
1. Go to Wyrmstooth island, go through the burrows, go to the village where the dragon flies over head.
4. See error CTD

**Expected behavior**
Im not sure ive never played this mission, just dont expect to crash and probably a big battle ensues.

**Crash log**

[crash-2023-02-16-08-20-34.log](https://github.com/CritLoren/Yggdrasil-VR/files/10753700/crash-2023-02-16-08-20-34.log)

**Desktop (please complete the following information):**
 - Yggdrasil VR version: 2.0-5
 - Storage type Yggdrasil VR is installed on: SSD
 - OS version: WIN 10
 - RAM: 16gb
 - CPU: r5 3600
 - GPU: 5700 xt AMD
 - Antivirus Windows Defender

**Comment by CritLoren** [comment]
Have you don'e any changes to the list? those issues show up if the synthesis water patch has discrepancies to the actual area data.

**Comment by SamielLJackson** [comment]
Other than vr fps stabilizer, and fsr i havent installed anything

**Comment by CritLoren** [comment]
Hmmm.. curious. How modding savvy are you? I might have some suggestions, but if you're not too savvy it might be worth re-running wabbajack. Don't delete anything, just select the same folder.

**Comment by SamielLJackson** [comment]
I also use oculus killer if that says anything

**Comment by CritLoren** [comment]
Try temporarily disabling the DynDOLOD and Occlusion esps. If that still causes issues disable the Synthesis patch too. that should make the problem go away (this is not a fix however, just for troubleshooting purposes; disabling these esps on a save will cause a lot of troubles down the line). Let me know if either of these makes that crash go away.

**Comment by SamielLJackson** [comment]
Will do, should i reneable them after the mission? If it will break my save i would rather just skip this mission and do something else.

**Comment by SamielLJackson** [comment]
These are disabled in Mo2? So dyndolod would be “2.0-5 dyndolod” searching occlusion into the mo2 filter doesn't show any mods.

**Comment by CritLoren** [comment]
not in the mods panel, in the esp panel - but disabling the dyndolod "mod" should disable both.

**Comment by SamielLJackson** [comment]
I was able to kill the dragon after disabling dyndolod, occlusion, and the synthesis patch. At first I disabled solely dyndolod and occlusion but got this crash. 
[crash-2023-02-17-18-13-12.log](https://github.com/CritLoren/Yggdrasil-VR/files/10769917/crash-2023-02-17-18-13-12.log)

**Comment by CritLoren** [comment]
that's fine, I expect other crashes after disabling synthesis Can you re-run synthesis? see if it works with it enabled after? not sure why it'd cause issues.

**Comment by SamielLJackson** [comment]
Leave everything off except synthesis?

**Comment by CritLoren** [comment]
keep dyndolod off, don't disable anything else, just run synthesis from within mo2

**Comment by SamielLJackson** [comment]
That worked on not crashing the game

**Comment by SamielLJackson** [comment]
So I rain synthesis with dyndolod and it helped a lot, I was able to actually delay the crash to fight the dragon twice (unfortunately still crashed twice). My third attempt it didn't crash and so far no crash. Thanks for your help.
