### ISSUE TITLE
CTD when leaving Darklight Tower

### ISSUE THREAD

**Issue by django747** [CritLoren/Yggdrasil-VR#93]
**Describe the bug**
Game crashes when trying to leave through either the entrance or exit of Darklight Tower

**To Reproduce**
See above

**Expected behavior**
It is expected to leave Darklight Tower and to return to the overworld without crashing

**Screenshots**
N/A

**Save**
See attached

**Crash log**
See attached

**Desktop (please complete the following information):**
 - Yggdrasil VR version: 2.0-5
 - Storage type Yggdrasil VR is installed on: SSD
 - OS version: Windows 10 Home v10.0.19041
 - RAM: 32gb
 - CPU: AMD Ryzen 7 3700X
 - GPU: Nvidia GeForce RTX 2070 SUPER
 - Antivirus: Windows Defender

**Additional context**
I wanted to note that I encountered a CTD twice when reaching the front steps of the tower. I got around this by approaching the tower from its right side, then hugging the tower wall until I got to the front door.

Plugins I have added:
Shadow of Skyrim.esp
SimplyBalanced.esp
TrueArmor.esp
MusicMerged.esp
MMM_OCW-patch.esp

[Darklight_Tower_CTD.zip](https://github.com/CritLoren/Yggdrasil-VR/files/11811913/Darklight_Tower_CTD.zip)

**Comment by CritLoren** [comment]
Sorry no support is given when running a modified list. yer on your own.
